### PR TITLE
Create Performance Review Requests Table

### PR DESCRIPTION
**Pull request by sselkef**
Created performance_review_requests table using knex migration.

To test in terminal:
1. cd /server
2. npm i
3. npm run db:drop
4. npm run db:create
5. npm run db:migrate
6. connect to database using: psql -U user -W taskbox
7. enter password
8. enter: SELECT * FROM performance_review_requests;

### CODE REVIEW

**Review by absmith22 — CHANGES_REQUESTED** [review]
This looks good except for the addition of tasks. Given that is a separate PR, and this is an older version of tasks, I think it risks overriding the correct tasks migration to an older version. In addition, the seed still has an invalid input for tasks.

**Comment by sselkef** [comment]
> This looks good except for the addition of tasks. Given that is a separate PR, and this is an older version of tasks, I think it risks overriding the correct tasks migration to an older version. In addition, the seed still has an invalid input for tasks.

I changed the base merge from the main branch to the tasks-migration branch. Not sure if this would fix it, but intuitively it should.

**Review by absmith22 — DISMISSED** [review]
This looks good and creates no conflicts.

**Review by aasthapatil — COMMENTED** [review]
Looks good

**Review by aasthapatil — DISMISSED** [review]

**Review by aasthapatil — APPROVED** [review]

**Pull request merged**
